* Changes to make package lintian clean
git-svn-id: svn+ssh://foss.ulster.ac.uk/svn/opus/trunk@44 54dc3e3f-df17-4cd7-99f1-b1610cd3c088

diff --git a/debian/opus.postinst b/debian/opus.postinst
--- a/debian/opus.postinst
+++ b/debian/opus.postinst
@@ -91,9 +91,10 @@ then
     then
       # We don't have valid root credentials
       have_password="no"
-      # Warn the user it's all gone fubar
-      db_input high opus/invalid_root_password || true
-      db_go
+      # Warn the user it's all gone fubar - but this makes lintian mad, remove for now
+      echo "WARNING! Invalid MySQL root credentials ..."
+      #db_input high opus/invalid_root_password || true
+      #db_go
     fi
   fi
   
