* More changes to improve Debian packaging
git-svn-id: svn+ssh://foss.ulster.ac.uk/svn/opus/trunk@27 54dc3e3f-df17-4cd7-99f1-b1610cd3c088

diff --git a/debian/opus.postinst b/debian/opus.postinst
--- a/debian/opus.postinst
+++ b/debian/opus.postinst
@@ -3,6 +3,33 @@
 # Source debconf library.
 . /usr/share/debconf/confmodule
 
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+case "$1" in
+    configure)
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# The main event
+
 if [ "$1" = "configure" ]
 then
   echo "writing debconf configuration ..."
@@ -62,14 +89,6 @@ then
   chmod 770 /usr/share/opus/templates_*
 fi
 
-
-# Create the database
-#echo "CREATE DATABASE"
-
-#if [ "$RET" = "false" ]; then
-#    /etc/init.d/subliminal_messages start "I like debian."
-#fi
-
 # Install a symlink from the config file to the /etc directory
 if [ "$1" = "configure" ] && [ ! -e /usr/share/opus/include/config.php ]
 then
@@ -102,3 +121,11 @@ fi
 
 
 # At some point, we might need to check for a few pear modules (mail ones)
+
+# Now for debhelper deep magic
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
